# Generated by Django 3.2.3 on 2021-05-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_persona_donador'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='correo',
            field=models.EmailField(default=True, max_length=254),
            preserve_default=False,
        ),
    ]
